language: java
jdk:
- oraclejdk7
after_success:
- mvn clean cobertura:cobertura coveralls:cobertura -DrepoToken=REPO_TOKEN
env:
  global:
    secure: bk0dKw+gHKbyuDQ4TrkSSW0dRTduzSXa5TaXkqUKq9HJCRMgrcbVHmjKuv72Vha/65ZfS9DQC/+n+jm+4hyqN3i72grIibzT/6rv0falnQhVMNZSrzHCm648/joCKRw65wZstlH8YL/ks1g5knOXMuW2Ig5is7aSqNcrcpUCNZ0=
